---
layout: cv
title: Tomas Fernandez' CV
---
# Tomas Fernandez
Data Analyst, Physicist, Husband, Father

<div id="webaddress">
<a href="https://www.linkedin.com/in/tomas-fernandez/">My LinkedIn profile</a>
| <a href="https://github.com/tomasfedz/tomasfedz.github.io">My GitHub portfolio</a>
</div>


## Currently

Data Analyst II at CorVel Corporation (working remotely), leveraging SQL, Python, and AI tools to drive strategic business decisions through data analysis and visualization.

### Specialized in

Data analysis, data visualization (Tableau, Power BI, Excel), SQL, machine learning models in Python (Decision Trees, Random Forests and Linear Regression), creation of C# applications, and physics-related computational applications.


### Research interests

Monte Carlo simulations, computational fluid dynamics (CFD), statistical analysis, data-driven decision-making, and process optimization.


## Education

`2023 - Present`
__Brigham Young University - Idaho, Rexburg, ID__

B.S. in Physics with a minor in Computational Physics
Key Projects: Monte Carlo simulation for cosmic ray propagation, CFD analysis for Formula SAE car (5% drag reduction), C# application for resource scheduling optimization.

`2018 - 2023`
__Ensign College, Salt Lake City, UT__

- Associate of Business Management - Data Analytics


## Experience

`February 2023 - Present`
__CorVel Corporation, Portland, OR__

#### Data Analyst II
Extract, manipulate, and analyze data using SQL to support decision-making.
Clean and preprocess data for integrity and visualization readiness.
Create Excel and Power BI dashboards and visualizations for stakeholders.
Collaborate with cross-functional teams to deliver actionable insights.

`September 2020 - February 2023`
__Weave Communications, Lehi, UT__

#### Sales Operations Analyst
Managed Salesforce lead database, increasing revenue per lead by 25%.
Led daily scrum meetings using agile methodologies.
Developed team-wide reports and dashboards for performance tracking.
Improved lead sourcing by 44% through event and conference strategies.
Managed JIRA for project tracking and process optimization.


<!-- ### Footer

Last updated: April 2025 -->